### ISSUE TITLE
m.2转接卡的蓝牙转接线问题

### ISSUE THREAD

**Issue by Diliya** [Ketuer/NUC9-i7QNX-hackintosh#2]
不知道老哥的转接卡蓝牙转接线是不是SH1.0，店家送的线太短了，够不到NUC9的USB接口（这接口我也没见过，问了一圈也没问到是啥接口），但是店家也不知道转接线是什么型号，想问下老哥是怎么解决的

**Comment by Ketuer** [comment]
为什么不直接买支持NUC9的，有卖的啊

**Comment by Diliya** [comment]
没搜到啊，有没有链接呢？

**Comment by Ketuer** [comment]
【淘宝】https://m.tb.cn/h.UIne0pY?tk=GNgedPTBjM0 CZ0001 「黑苹果免驱BCM94360CD/CS2/NUC8无线网卡台式机m.2 NGFF转接卡」
点击链接直接打开 或者 淘宝搜索直接打开
